apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend/deploy.yml
- backend/service.yml
- frontend/deploy.yml
- frontend/service.yml


images:
- name: 591853006687.dkr.ecr.us-east-1.amazonaws.com/workshop/production/backend
  newName: 591853006687.dkr.ecr.us-east-1.amazonaws.com/workshop/production/backend
  newTag: ec9eb54a6e32554fcef9286247bb2878c5e69757
- name: 591853006687.dkr.ecr.us-east-1.amazonaws.com/workshop/production/frontend
  newName: 591853006687.dkr.ecr.us-east-1.amazonaws.com/workshop/production/frontend
  newTag: v1.0
